apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: nfs-pvc
  nfs:
    path: /nfs
    server: nfs_server_ip
    readOnly: true

