apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 600Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: nfs-pvc
  nfs:
    path: /nfs 
    server: x.x.x.x # nfs server private ip
    readOnly: true

