kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: username
  name: rfam-user-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "jobs"] # replicasets may not be necessary
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # perhaps remove delete, update and patch
