apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: $USERID
spec:
  groups:
  - system:authenticated
  request: # replace with output from shell command: cat rfam-user-k8s.csr | base64 | tr -d '\n'
  usages:
  - client auth
