name: Singularity Build
on: workflow_call


jobs:
  run_conversion:
    name: "Pull docker image and convert"
    runs-on: ubuntu-latest

    container:
      image: quay.io/singularity/singularity:v3.8.1
      options: --privileged

    steps:
      - name: "Pull image"
        run: |
          singularity pull  --name rfam-rfam-families-latest.sif docker://rfam/family-pipeline:latest
      - name: "Push to ghcr"
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io
          singularity push rfam-rfam-families-latest.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest
